/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Produto;
import model.dao.ClienteDAO;
import model.dao.ProdutosDAO;

/**
 *
 * @author beatrizlira
 */
public class Estoque extends javax.swing.JFrame {

    /**
     * Creates new form ListaProdutos
     */
    public Estoque() {
        initComponents();
      
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        pnlAdicaoProdutos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        txtCodigoProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValorProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQuantidadeProduto = new javax.swing.JTextField();
        btnInserirProduto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        pnlListaProdutos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaProdutos = new javax.swing.JTable();
        btnExcluirProduto = new javax.swing.JButton();
        btnEditarProduto = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        pnlAdicaoProdutos.setBackground(new java.awt.Color(255, 255, 255));
        pnlAdicaoProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 20))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Nome do Produto:");

        txtNomeProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoActionPerformed(evt);
            }
        });

        txtCodigoProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProdutoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Quantidade:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Valor:");

        txtValorProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtValorProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorProdutoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("Código:");

        txtQuantidadeProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtQuantidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeProdutoActionPerformed(evt);
            }
        });

        btnInserirProduto.setBackground(new java.awt.Color(247, 138, 30));
        btnInserirProduto.setText("INSERIR NOVO PRODUTO");
        btnInserirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirProdutoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Marca");

        txtMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Categoria");

        txtCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlAdicaoProdutosLayout = new javax.swing.GroupLayout(pnlAdicaoProdutos);
        pnlAdicaoProdutos.setLayout(pnlAdicaoProdutosLayout);
        pnlAdicaoProdutosLayout.setHorizontalGroup(
            pnlAdicaoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicaoProdutosLayout.createSequentialGroup()
                .addGroup(pnlAdicaoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInserirProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addGroup(pnlAdicaoProdutosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAdicaoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdicaoProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeProduto))
                            .addGroup(pnlAdicaoProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(119, 119, 119)
                                .addComponent(txtMarca))
                            .addGroup(pnlAdicaoProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(88, 88, 88)
                                .addComponent(txtCategoria))
                            .addGroup(pnlAdicaoProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txtQuantidadeProduto))
                            .addGroup(pnlAdicaoProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(txtValorProduto))
                            .addGroup(pnlAdicaoProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtCodigoProduto)))))
                .addContainerGap())
        );
        pnlAdicaoProdutosLayout.setVerticalGroup(
            pnlAdicaoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicaoProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdicaoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdicaoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdicaoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdicaoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdicaoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdicaoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(btnInserirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pnlListaProdutos.setBackground(new java.awt.Color(255, 255, 255));
        pnlListaProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTA DE PRODUTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 20))); // NOI18N

        tblListaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Nome do Produto", "Marca", "Categoria", "Quantidade", "Valor", "Código do Produto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaProdutos);

        btnExcluirProduto.setBackground(new java.awt.Color(247, 138, 30));
        btnExcluirProduto.setText("Excluir Produto");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        btnEditarProduto.setBackground(new java.awt.Color(247, 138, 30));
        btnEditarProduto.setText("Editar Produto");
        btnEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProdutoActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlListaProdutosLayout = new javax.swing.GroupLayout(pnlListaProdutos);
        pnlListaProdutos.setLayout(pnlListaProdutosLayout);
        pnlListaProdutosLayout.setHorizontalGroup(
            pnlListaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListaProdutosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlListaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListaProdutosLayout.createSequentialGroup()
                        .addComponent(btnEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListaProdutosLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addGap(53, 53, 53))))
        );
        pnlListaProdutosLayout.setVerticalGroup(
            pnlListaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListaProdutosLayout.createSequentialGroup()
                .addGroup(pnlListaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlListaProdutosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.setBackground(new java.awt.Color(0, 71, 141));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ESTOQUE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jLabel1)
                .addContainerGap(1016, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 71, 141));

        jButton1.setText("VOLTAR AO MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAdicaoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlListaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAdicaoProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlListaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirProdutoActionPerformed

        if(txtNomeProduto.getText().equals("")){
                   JOptionPane.showMessageDialog(this, "O nome do produto precisa ser preenchido");
            return; }
            else if(txtQuantidadeProduto.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "A quantidade do produto precisa ser preenchida");
                         return;
            }
              else if(txtMarca.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "A marca do produto precisa ser preenchida");
                         return;
            }
            
            else if(txtCategoria.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "A categoria do produto precisa ser preenchida");
                         return;
            }
            else if(txtValorProduto.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "O valor do produto precisa ser preenchido");
                         return;
                         
            } else if(txtCodigoProduto.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "O código do produto precisa ser preenchido");
                 return;
            }
       
        
        
             try {
        
        double retornoValor = Double.parseDouble(txtValorProduto.getText());
        
        } catch (NumberFormatException a) {

        JOptionPane.showMessageDialog(this, "Digite apenas números no campo valor");
        return;
        
        } 
       
       try {
        
        int retornoQuantidade = Integer.parseInt(txtQuantidadeProduto.getText());
        
} catch (NumberFormatException a) {
        JOptionPane.showMessageDialog(this, "Digite apenas números no campo quantidade");
        return;
    }
       
       try {
        
        int retornoCod = Integer.parseInt(txtCodigoProduto.getText());
        
            } catch (NumberFormatException a) {

        JOptionPane.showMessageDialog(this, "Digite apenas números no campo código");
        return;
        
    }
       
       String nome = txtNomeProduto.getText();
       String valor = (txtValorProduto.getText());
       String quantidade =(txtQuantidadeProduto.getText());
       String codigo = txtCodigoProduto.getText();
       
       DefaultTableModel tabelaProduto = (DefaultTableModel) tblListaProdutos.getModel();
       Object[] novoProduto = new Object[]{
           nome,
           quantidade,
          valor,
          codigo
       };
       
           Produto p = new Produto();
        ProdutosDAO dao = new ProdutosDAO();

       
        p.setNomeProduto(txtNomeProduto.getText());
        p.setMarca(txtMarca.getText());
        p.setCategoria(txtCategoria.getText());
        p.setQuantidade(Integer.parseInt(txtQuantidadeProduto.getText()));
        p.setValor(Double.parseDouble(txtValorProduto.getText()));
        p.setCodigo(Integer.parseInt(txtCodigoProduto.getText()));
      
    
     
         

            dao.create(p);
        
    }//GEN-LAST:event_btnInserirProdutoActionPerformed

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void txtValorProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorProdutoActionPerformed

    private void btnEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProdutoActionPerformed

        if(txtNomeProduto.getText().equals("")){
                   JOptionPane.showMessageDialog(this, "O nome do produto precisa ser preenchido");
            return; }
            else if(txtQuantidadeProduto.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "A quantidade do produto precisa ser preenchida");
                         return;
            }
            else if(txtMarca.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "A marca do produto precisa ser preenchida");
                         return;
            }
            
            else if(txtCategoria.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "A categoria do produto precisa ser preenchida");
                         return;
            }
            else if(txtValorProduto.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "O valor do produto precisa ser preenchido");
                         return;
                         
            } else if(txtCodigoProduto.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "O código do produto precisa ser preenchido");
                 return;
            }
       
        
        
             try {
        
              double retornoValor = Double.parseDouble(txtValorProduto.getText());
        
        } catch (NumberFormatException a) {

        JOptionPane.showMessageDialog(this, "Digite apenas números no campo valor");
        return;
        
        } 
       
       try {
        
        int retornoQuantidade = Integer.parseInt(txtQuantidadeProduto.getText());
        
} catch (NumberFormatException a) {
        JOptionPane.showMessageDialog(this, "Digite apenas números no campo quantidade");
        return;
    }
       
       try {
        
        int retornoCod = Integer.parseInt(txtCodigoProduto.getText());
        
            } catch (NumberFormatException a) {

        JOptionPane.showMessageDialog(this, "Digite apenas números no campo código");
        return;
        
    }
        if(tblListaProdutos.getSelectedRow() != 1){
           Produto p = new Produto();
        ProdutosDAO dao = new ProdutosDAO();

       
       p.setNomeProduto(txtNomeProduto.getText());
        p.setMarca(txtMarca.getText());
        p.setCategoria(txtCategoria.getText());
        p.setQuantidade(Integer.parseInt(txtQuantidadeProduto.getText()));
        p.setValor(Double.parseDouble(txtValorProduto.getText()));
        p.setCodigo(Integer.parseInt(txtCodigoProduto.getText()));
      
        p.setId((int)tblListaProdutos.getValueAt(tblListaProdutos.getSelectedRow(),0));
            dao.update(p);
            readJTable();
       }
    }//GEN-LAST:event_btnEditarProdutoActionPerformed

    private void txtCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProdutoActionPerformed

    private void tblListaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaProdutosMouseClicked
             if(tblListaProdutos.getSelectedRow() != -1){
            txtNomeProduto.setText(tblListaProdutos.getValueAt(tblListaProdutos.getSelectedRow(), 1).toString());
            txtMarca.setText(tblListaProdutos.getValueAt(tblListaProdutos.getSelectedRow(), 2).toString());
             txtCategoria.setText(tblListaProdutos.getValueAt(tblListaProdutos.getSelectedRow(), 3).toString());
            txtQuantidadeProduto.setText(tblListaProdutos.getValueAt(tblListaProdutos.getSelectedRow(), 4).toString());
            txtValorProduto.setText(tblListaProdutos.getValueAt(tblListaProdutos.getSelectedRow(), 5).toString());
            txtCodigoProduto.setText(tblListaProdutos.getValueAt(tblListaProdutos.getSelectedRow(), 6).toString());
           
            
        }
        
    }//GEN-LAST:event_tblListaProdutosMouseClicked

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
             if (tblListaProdutos.getSelectedRow()!= -1) {
            
       Produto produto = new Produto();
        ProdutosDAO dao = new ProdutosDAO();
        
      
        produto.setId((int)tblListaProdutos.getValueAt(tblListaProdutos.getSelectedRow(),0));
            
         dao.Excluir(produto);
          readJTable();
      }
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void txtQuantidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeProdutoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        readJTable();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

           public void readJTable(){
        DefaultTableModel modelo =(DefaultTableModel) tblListaProdutos.getModel();
        modelo.setNumRows(0);
        ProdutosDAO dao = new ProdutosDAO();
        
        for(Produto p: dao.read()){
            modelo.addRow(new Object[]{
               p.getId(),
                p.getNomeProduto(),
                p.getMarca(),
                p.getCategoria(),
                p.getQuantidade(),
                p.getValor(),
                p.getCodigo()
            
                
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditarProduto;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnInserirProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlAdicaoProdutos;
    private javax.swing.JPanel pnlListaProdutos;
    private javax.swing.JTable tblListaProdutos;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtQuantidadeProduto;
    private javax.swing.JTextField txtValorProduto;
    // End of variables declaration//GEN-END:variables
    
    public boolean inserirProduto(){
        if(txtNomeProduto.getText().equals("")){
                   JOptionPane.showMessageDialog(this, "O nome do produto precisa ser preenchido");
            return false; }
            else if(txtQuantidadeProduto.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "A quantidade do produto precisa ser preenchida");
                         return false;
            }
            else if(txtValorProduto.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "O valor do produto precisa ser preenchido");
                         return false;
                         
            } else if(txtCodigoProduto.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "O código do produto precisa ser preenchido");
                 return false;
            }
       
        
        
             try {
        
              double retornoValor = Double.parseDouble(txtValorProduto.getText());
         
        
        } catch (NumberFormatException a) {

        JOptionPane.showMessageDialog(this, "Digite apenas números no campo valor");
        return false;
        
        } 
       
       try {
        
        int retornoQuantidade = Integer.parseInt(txtQuantidadeProduto.getText());
        
} catch (NumberFormatException a) {
        JOptionPane.showMessageDialog(this, "Digite apenas números no campo quantidade");
        return false;
    }
       
       try {
        
        int retornoCod = Integer.parseInt(txtCodigoProduto.getText());
        
            } catch (NumberFormatException a) {

        JOptionPane.showMessageDialog(this, "Digite apenas números no campo código");
        return false;
        
    }
       return true;
       
       };
       
    

    public void editarProduto(){
         int linhaSelecionada = tblListaProdutos.getSelectedRow();
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this, "Nenhum item selecionado, tente novamente");
        } else if(txtNomeProduto.getText().equals("")){
                   JOptionPane.showMessageDialog(this, "O nome do produto precisa ser preenchido");
                    return;
        }else if(txtQuantidadeProduto.getText().equals("")){
           JOptionPane.showMessageDialog(this, "A quantidade do produto precisa ser preenchida");
        }  else if(txtValorProduto.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "O valor do produto precisa ser preenchido");
            } else if(txtCodigoProduto.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "O código do produto precisa ser preenchido");
            }
        else{
           tblListaProdutos.setValueAt(txtNomeProduto.getText(), tblListaProdutos.getSelectedRow(), 0);
           tblListaProdutos.setValueAt(txtQuantidadeProduto.getText(), tblListaProdutos.getSelectedRow(), 1);
           tblListaProdutos.setValueAt(txtValorProduto.getText(), tblListaProdutos.getSelectedRow(), 2);
           tblListaProdutos.setValueAt(txtCodigoProduto.getText(), tblListaProdutos.getSelectedRow(), 3);
        }   
    }

    public void listarProduto(){
        if(tblListaProdutos.getSelectedRow() != -1){
            txtNomeProduto.setText(tblListaProdutos.getValueAt(tblListaProdutos.getSelectedRow(), 0).toString());
            txtQuantidadeProduto.setText(tblListaProdutos.getValueAt(tblListaProdutos.getSelectedRow(), 1).toString());
            txtValorProduto.setText(tblListaProdutos.getValueAt(tblListaProdutos.getSelectedRow(), 2).toString());
            txtCodigoProduto.setText(tblListaProdutos.getValueAt(tblListaProdutos.getSelectedRow(), 3).toString());
        }
    }
    
    public void excluirProduto(){
         int linhaSelecionada = tblListaProdutos.getSelectedRow();
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this, "Nenhum produto selecionado, tente novamente");
            
            
        } else{
             DefaultTableModel tabelaProduto = (DefaultTableModel) tblListaProdutos.getModel();
             tabelaProduto.removeRow(linhaSelecionada);
              JOptionPane.showMessageDialog(this, "Produto Excluido");
            
        }
    }
}
